/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    // MUHIM: extend o'rniga to'liq override — inconsistency oldini oladi
    fontSize: {
      '2xs': ['10px', { lineHeight: '14px', letterSpacing: '0.04em' }],
      'xs':  ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
      'sm':  ['13px', { lineHeight: '18px', letterSpacing: '-0.01em' }],
      'base':['14px', { lineHeight: '20px', letterSpacing: '-0.01em' }],
      'md':  ['15px', { lineHeight: '22px', letterSpacing: '-0.01em' }],
      'lg':  ['16px', { lineHeight: '24px', letterSpacing: '-0.015em' }],
      'xl':  ['18px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
      '2xl': ['22px', { lineHeight: '30px', letterSpacing: '-0.025em' }],
      '3xl': ['26px', { lineHeight: '34px', letterSpacing: '-0.03em' }],
      '4xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.035em' }],
    },
    borderRadius: {
      'none': '0px',
      'sm':   'var(--r-sm)',   /* 8px */
      'md':   'var(--r-md)',   /* 12px */
      'lg':   'var(--r-lg)',   /* 16px */
      'xl':   'var(--r-xl)',   /* 20px */
      'full': 'var(--r-full)',
      DEFAULT: 'var(--r-lg)',
    },
    extend: {
      colors: {
        'edu-bg':        'var(--edu-bg)',
        'edu-surface':   'var(--edu-surface)',
        'edu-surface-2': 'var(--edu-surface-2)',
        'edu-surface-3': 'var(--edu-surface-3)',
        'edu-border':    'var(--edu-border)',
        'edu-border-2':  'var(--edu-border-2)',
        'edu-border-focus':'var(--edu-border-focus)',
        'edu-text':      'var(--edu-text)',
        'edu-text-2':    'var(--edu-text-2)',
        'edu-muted':     'var(--edu-muted)',
        'edu-muted-2':   'var(--edu-muted-2)',
        'edu-primary':   'var(--edu-primary)',
        'edu-primary-h': 'var(--edu-primary-h)',
        'edu-primary-l': 'var(--edu-primary-l)',
        'edu-primary-xl':'var(--edu-primary-xl)',
        'edu-accent':    'var(--edu-accent)',
        'edu-accent-h':  'var(--edu-accent-h)',
        'edu-accent-l':  'var(--edu-accent-l)',
        'edu-urgent':    'var(--edu-urgent)',
        'edu-urgent-l':  'var(--edu-urgent-l)',
        'edu-warn':      'var(--edu-warn)',
        'edu-warn-l':    'var(--edu-warn-l)',
        'edu-success':   'var(--edu-success)',
        'edu-vip':       'var(--edu-vip)',
        'edu-vip-l':     'var(--edu-vip-l)',
        'edu-info':      'var(--edu-info)',
        'edu-info-l':    'var(--edu-info-l)',
        // Status
        'status-open':       'var(--status-open)',
        'status-assigned':   'var(--status-assigned)',
        'status-progress':   'var(--status-progress)',
        'status-review':     'var(--status-review)',
        'status-completed':  'var(--status-completed)',
        'status-canceled':   'var(--status-canceled)',
        'status-disputed':   'var(--status-disputed)',
      },
      boxShadow: {
        'sm':   'var(--shadow-sm)',
        'md':   'var(--shadow-md)',
        'lg':   'var(--shadow-lg)',
        'btn':  'var(--shadow-btn)',
      },
      spacing: {
        'safe-b':  'env(safe-area-inset-bottom)',
        'nav':     '64px',
        'pb-nav':  'calc(64px + env(safe-area-inset-bottom) + 8px)',
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '24': '96px',
      },
      animation: {
        'shimmer':      'shimmer 1.6s linear infinite',
        'fade-in':      'fadeIn 220ms var(--ease-out) both',
        'slide-up':     'slideUp 360ms var(--ease-out) both',
        'scale-in':     'scaleIn 220ms var(--ease-spring) both',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-400px 0' },
          '100%': { backgroundPosition: '400px 0'  },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)'    },
        },
        scaleIn: {
          '0%':   { opacity: '0', transform: 'scale(0.9)'  },
          '100%': { opacity: '1', transform: 'scale(1)'    },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '0.6' },
          '50%':      { opacity: '1'   },
        },
      },
    },
  },
  plugins: [],
};
